#!/usr/bin/env sh
# Origin: /tmp/tauri-stop-dev-processes.sh, likely generated by Tauri tooling.
# Purpose: recursively identify and kill child development processes.
# Warning: unreviewed and destructive to the supplied process tree. The
# implementation has been minimally hardened during archival.
set -eu

if [ "$#" -ne 1 ]; then
    echo "usage: $0 PID" >&2
    exit 2
fi

getcpid() {
    cpids=$(pgrep -P "$1" || true)
    for cpid in $cpids; do
        echo "$cpid"
        getcpid "$cpid"
    done
}

getcpid "$1" | xargs -r kill --
